---
output: rmarkdown::github_document
---

# **Ethiopian Conflict: CNN-International (CNNI)'s Coverage**

Triggered by a thought-provoking [thread](https://twitter.com/mekdes_asefa/status/1439266110679965708) by [Mekdes Asefa](https://twitter.com/mekdes_asefa)

## The start of the conflict
> **November 03, 2021** 

## How has cnni covered the conflict? 

> See it for yourself on [Google News](https://google.com/search?q=site:https://cnn.com+after:2020-11-02+"Ethiopia"+AND+"Tigray"+-"Covid"+-"Nile"+&tbm=nws+&lr=lang_en+tbs=sbd:1+)

## Goal of this repo

* Produce a list of CNN's stories ever since the conflict broke out, November 4, 2020. 

## So far

- [x] **Articles**: 
    I have managed to scrape news articles that CNN published ever since. You can find the details about these news articles in this [csv file](articles-meta.csv), in the same directory. 

```{r, results='asis', tidy=TRUE}
articles = read.csv('articles-meta.csv')
articles$url = with(articles, 
                    sprintf('<a href="%s">%s</a>', 
                            url, basename(sub('/index.html', '', url)))
                    )
# DT::datatable(articles, 
#              options = list(pageLength=5), filter = "top", escape = F)

knitr::kable(head(articles), 
             format = 'markdown', booktab=T)
```


<br> <br>

CNN does not produce news only in an article form. There are live news coverages with a collection of short "posts" (e.g. [here](https://edition.cnn.com/africa/live-news/ethiopia-conflict-updates-11-5-intl/index.html)), and video reporting (e.g. [here](https://edition.cnn.com/videos/world/2021/06/13/ethiopia-famine-thousands-facing-starvation-busari-lklv-nr-intl-vpx.cnn)) as well. This repo contains details about such coverage too. 

- [x] **Live-news coverage** [here](live-news-articles.csv)

- [x] **Video reports** [here](video-reports.csv)


## To-Do

- [ ] Automate with `github actions`
- [ ] Do an exploratory analysis
- [ ] Download full body of the articles and do some text analysis
- [ ] Download images and videos
- [ ] Do the same for Reuters, BBC, and the likes




